let shopItemsData = [
  {
    id: "LCRC2L",
    name: "Nước rửa chén organic Layer Clean túi 2L",
    price: 135000,
    desc: "100% tự nhiên.",
    img: "images/LC-RC-2L.png",
    brand: "Layer Clean",
  },
  {
    id: "LCRC5L",
    name: "Nước rửa chén organic Layer Clean can 5L",
    price: 231075,
    desc: "100% tự nhiên.",
    img: "images/LC-RC-5L.png",
    brand: "Layer Clean",
  },
  {
    id: "LCRC800ml",
    name: "Nước rửa chén organic Layer Clean chai 800ml",
    price: 67500,
    desc: "100% tự nhiên.",
    img: "images/LC-RC-800ml.png",
    brand: "Layer Clean",
  },
  {
    id: "LCNG5L",
    name: "Nước giặt sinh học Layer Clean 5L Hương gió biển",
    price: 296250,
    desc: "100% tự nhiên.",
    img: "images/LC-NG-5L.png",
    brand: "Layer Clean",
  },
  {
    id: "MHNG2L",
    name: "Nước Giặt Organic an toàn cho bé Minh Hồng chai 2L",
    price: 126000,
    desc: "100% tự nhiên.",
    img: "images/MH-NG-2L.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNG4L2",
    name: "Nước Giặt Hữu cơ Organic Minh Hồng chai 4.2L",
    price: 210700,
    desc: "100% tự nhiên.",
    img: "images/MH-NG-4.2L.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNLS1L7",
    name: "Nước Lau Sàn sinh học hữu cơ Minh Hồng chai 1.7L",
    price: 105000,
    desc: "100% tự nhiên.",
    img: "images/MH-NLS-1.7L.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNLS4L2",
    name: "Nước Lau Sàn sinh học Minh Hồng an toàn cho bé chai 4.2L",
    price: 245000,
    desc: "100% tự nhiên.",
    img: "images/MH-NLS-4.2L.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNRC500ml",
    name: "Nước rửa chén sinh học Minh Hồng chai 500ml",
    price: 42000,
    desc: "100% tự nhiên.",
    img: "images/MH-NRC-500ml.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNRC1L7",
    name: "Nước rửa chén an toàn cho bé Minh Hồng chai 1.7L",
    price: 119000,
    desc: "100% tự nhiên.",
    img: "images/MH-NRC-1.7L.png",
    brand: "Minh Hồng",
  },
  {
    id: "MHNRC4L2",
    name: "Nước rửa chén sinh học Minh Hồng chai 4.2L tiết kiệm",
    price: 204400,
    desc: "100% tự nhiên.",
    img: "images/MH-NRC-4.2L.png",
    brand: "Minh Hồng",
  },
];
